#!/bin/sh -e

    echo "sammle Netzwerkdaten des RasPi ... "

    # hostname ermitteln und in Variable speichern
    info_hostname=$(hostname)
    echo $info_hostname

    ### eth0 ###
    # MAC-Adresse von eth0 ermitteln und in Variable speichern
    info_eth0_mac=$(ip link show dev eth0 | grep -oE 'link/ether ([a-f0-9]{2}:){5}[a-f0-9]{2}' | cut -d' ' -f2)
    echo "info_eth0_mac: " $info_eth0_mac

    # IPv4-Adresse fuer eth0 ermitteln und in Variable speichern
    info_eth0_ipv4=$(ip addr show dev eth0 | grep -oE 'inet ([0-9]{1,3}.){3}[0-9]{1,3}' | cut -d' ' -f2)
    echo "info_eth0_ipv4: " $info_eth0_ipv4 

    ### wlan0 ###
    # MAC-Adresse von wlan0 ermitteln und in Variable speichern
    info_wlan0_mac=$(ip link show dev wlan0 | grep -oE 'link/ether ([a-f0-9]{2}:){5}[a-f0-9]{2}' | cut -d' ' -f2)
    echo "info_wlan0_mac: " $info_wlan0_mac

    # IPv4-Adresse fuer wlan0 ermitteln und in Variable speichern
    info_wlan0_ipv4=$(ip addr show dev wlan0 | grep -oE 'inet ([0-9]{1,3}.){3}[0-9]{1,3}' | cut -d' ' -f2)
    echo "info_wlan0_ipv4: " $info_wlan0_ipv4

    # Daten an Webserver per GET-Methode übermitteln
    echo "sende Netzwerkdaten des RasPi ... "
    wget --delete-after --quiet --no-check-certificate "https://t1ntan.crew.c-base.org/wimd/receive.php?hostname=$info_hostname&eth0_mac=$info_eth0_mac&eth0_ipv4=$info_eth0_ipv4&wlan0_mac=$info_wlan0_mac&wlan0_ipv4=$info_wlan0_ipv4"

